//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CollectionPoint
{
    public CollectionPoint()
    {
        this.Departments = new HashSet<Department>();
    }

    public int CollectionPoint_ID { get; set; }
    public string CollectionPoint_Name { get; set; }
    public Nullable<System.TimeSpan> CollectionPoint_Time { get; set; }

    public virtual ICollection<Department> Departments { get; set; }
}

public partial class Department
{
    public Department()
    {
        this.Department_Orders = new HashSet<Department_Orders>();
        this.Employees = new HashSet<Employee>();
        this.IOUs = new HashSet<IOU>();
        this.Product_Disbursement = new HashSet<Product_Disbursement>();
        this.Employees1 = new HashSet<Employee>();
        this.IOUs1 = new HashSet<IOU>();
    }

    public string Department_ID { get; set; }
    public string Department_Name { get; set; }
    public Nullable<int> Department_Head { get; set; }
    public Nullable<int> Contact_Name { get; set; }
    public Nullable<int> Contact_Number { get; set; }
    public Nullable<int> Fax_Number { get; set; }
    public Nullable<int> Department_Representative { get; set; }
    public int CollectionPoint_ID { get; set; }
    public Nullable<int> Department_Authorized_Person { get; set; }

    public virtual CollectionPoint CollectionPoint { get; set; }
    public virtual Employee Employee { get; set; }
    public virtual ICollection<Department_Orders> Department_Orders { get; set; }
    public virtual ICollection<Employee> Employees { get; set; }
    public virtual ICollection<IOU> IOUs { get; set; }
    public virtual ICollection<Product_Disbursement> Product_Disbursement { get; set; }
    public virtual ICollection<Employee> Employees1 { get; set; }
    public virtual ICollection<IOU> IOUs1 { get; set; }
}

public partial class Department_Orders
{
    public int Department_Orders_ID { get; set; }
    public string Department_ID { get; set; }
    public string Item_ID { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public Nullable<int> Requisition_Quantity { get; set; }
    public Nullable<int> Fulfilled_Quantity { get; set; }
    public Nullable<int> IOU_Quantity { get; set; }
    public Nullable<int> Return_Quantity { get; set; }

    public virtual Department Department { get; set; }
    public virtual Stationery_Catalogue Stationery_Catalogue { get; set; }
}

public partial class Employee
{
    public Employee()
    {
        this.Departments = new HashSet<Department>();
        this.Stationery_Requisition = new HashSet<Stationery_Requisition>();
        this.Voucher_Request = new HashSet<Voucher_Request>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public string Department_ID { get; set; }
    public Nullable<int> Reportsto { get; set; }

    public virtual ICollection<Department> Departments { get; set; }
    public virtual Department Department { get; set; }
    public virtual Department Department1 { get; set; }
    public virtual ICollection<Stationery_Requisition> Stationery_Requisition { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Voucher_Request> Voucher_Request { get; set; }
}

public partial class IOU
{
    public string IOU_ID { get; set; }
    public string Department_ID { get; set; }
    public string Item_Number { get; set; }
    public Nullable<int> IOU_Quantity { get; set; }
    public string Status { get; set; }

    public virtual Department Department { get; set; }
    public virtual Department Department1 { get; set; }
    public virtual Stationery_Catalogue Stationery_Catalogue { get; set; }
}

public partial class iou_list_view
{
    public string Description { get; set; }
    public string Department_Name { get; set; }
    public Nullable<int> IOU_Quantity { get; set; }
    public Nullable<int> Total_Quantity { get; set; }
    public string Item_Number { get; set; }
}

public partial class Product_Disbursement
{
    public int Product_Disbursement_ID { get; set; }
    public string Item_ID { get; set; }
    public string Department_ID { get; set; }
    public Nullable<int> IOU_Quantity { get; set; }
    public Nullable<int> Requested_Quantity { get; set; }
    public Nullable<int> Delivery_Quantity { get; set; }
    public Nullable<int> Return_Quantity { get; set; }
    public string Signature { get; set; }
    public Nullable<System.DateTime> Delivery_Date { get; set; }
    public string Reason { get; set; }

    public virtual Department Department { get; set; }
    public virtual Stationery_Catalogue Stationery_Catalogue { get; set; }
}

public partial class Purchase_Order
{
    public Purchase_Order()
    {
        this.Purchase_Order_Details = new HashSet<Purchase_Order_Details>();
    }

    public int Order_ID { get; set; }
    public int User_ID { get; set; }
    public Nullable<System.DateTime> Order_Date { get; set; }

    public virtual ICollection<Purchase_Order_Details> Purchase_Order_Details { get; set; }
}

public partial class Purchase_Order_Details
{
    public int Order_ID { get; set; }
    public string Item_Number { get; set; }
    public string Supplier_ID { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string Status { get; set; }

    public virtual Purchase_Order Purchase_Order { get; set; }
    public virtual Stationery_Catalogue Stationery_Catalogue { get; set; }
    public virtual Supplier Supplier { get; set; }
}

public partial class Requisition_Items
{
    public int Requisition_ID { get; set; }
    public string Item_ID { get; set; }
    public Nullable<int> Quantity { get; set; }

    public virtual Stationery_Requisition Stationery_Requisition { get; set; }
    public virtual Stationery_Catalogue Stationery_Catalogue { get; set; }
    public virtual Stationery_Requisition Stationery_Requisition1 { get; set; }
}

public partial class Role
{
    public Role()
    {
        this.Users = new HashSet<User>();
    }

    public int RoleId { get; set; }
    public string RoleName { get; set; }

    public virtual ICollection<User> Users { get; set; }
}

public partial class Security_Question
{
    public int Question_ID { get; set; }
    public string Question { get; set; }
}

public partial class stationary_requisition_view
{
    public int Requisition_ID { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public string Department_Name { get; set; }
    public Nullable<int> Quantity { get; set; }
}

public partial class Stationery_Catalogue
{
    public Stationery_Catalogue()
    {
        this.Department_Orders = new HashSet<Department_Orders>();
        this.IOUs = new HashSet<IOU>();
        this.Product_Disbursement = new HashSet<Product_Disbursement>();
        this.Purchase_Order_Details = new HashSet<Purchase_Order_Details>();
        this.Requisition_Items = new HashSet<Requisition_Items>();
        this.Voucher_Request = new HashSet<Voucher_Request>();
        this.Supplier_Item = new HashSet<Supplier_Item>();
    }

    public string Item_Number { get; set; }
    public string Category { get; set; }
    public string Description { get; set; }
    public Nullable<int> Reorder_Level { get; set; }
    public Nullable<int> Reorder_Quantity { get; set; }
    public string Measure_Unit { get; set; }
    public Nullable<double> Price { get; set; }
    public Nullable<int> Total_Quantity { get; set; }

    public virtual ICollection<Department_Orders> Department_Orders { get; set; }
    public virtual ICollection<IOU> IOUs { get; set; }
    public virtual ICollection<Product_Disbursement> Product_Disbursement { get; set; }
    public virtual ICollection<Purchase_Order_Details> Purchase_Order_Details { get; set; }
    public virtual ICollection<Requisition_Items> Requisition_Items { get; set; }
    public virtual ICollection<Voucher_Request> Voucher_Request { get; set; }
    public virtual ICollection<Supplier_Item> Supplier_Item { get; set; }
}

public partial class Stationery_Requisition
{
    public Stationery_Requisition()
    {
        this.Requisition_Items = new HashSet<Requisition_Items>();
        this.Requisition_Items1 = new HashSet<Requisition_Items>();
    }

    public int Requisition_ID { get; set; }
    public int User_ID { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public string Status { get; set; }
    public string Reason { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual ICollection<Requisition_Items> Requisition_Items { get; set; }
    public virtual ICollection<Requisition_Items> Requisition_Items1 { get; set; }
}

public partial class Supplier
{
    public Supplier()
    {
        this.Purchase_Order_Details = new HashSet<Purchase_Order_Details>();
        this.Supplier_Item = new HashSet<Supplier_Item>();
    }

    public string Supplier_ID { get; set; }
    public string Supplier_Name { get; set; }
    public string Contact_Name { get; set; }
    public Nullable<int> Contact_Number { get; set; }
    public Nullable<int> Fax_Number { get; set; }
    public string Address { get; set; }
    public string GST_Number { get; set; }
    public string Remarks { get; set; }

    public virtual ICollection<Purchase_Order_Details> Purchase_Order_Details { get; set; }
    public virtual ICollection<Supplier_Item> Supplier_Item { get; set; }
}

public partial class Supplier_Item
{
    public int Supplier_Item_ID { get; set; }
    public string Supplier_ID { get; set; }
    public string Item_Number { get; set; }
    public string Rank { get; set; }
    public Nullable<double> Price { get; set; }

    public virtual Stationery_Catalogue Stationery_Catalogue { get; set; }
    public virtual Supplier Supplier { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class User
{
    public int UserId { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public Nullable<System.DateTime> LastLoginDate { get; set; }
    public Nullable<int> RoleId { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Role Role { get; set; }
}

public partial class UserActivation
{
    public int UserId { get; set; }
    public System.Guid ActivationCode { get; set; }
}

public partial class Voucher_Request
{
    public int Voucher_ID { get; set; }
    public string Item_ID { get; set; }
    public Nullable<int> User_ID { get; set; }
    public System.DateTime Date { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string Reason { get; set; }
    public string Status { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Stationery_Catalogue Stationery_Catalogue { get; set; }
}

public partial class AddtoRetrievel_Result
{
    public int Requisition_ID { get; set; }
    public string Item_ID { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public string Department_ID { get; set; }
}

public partial class AddtoRetrievelnew_Result
{
    public int Requisition_ID { get; set; }
    public string Status { get; set; }
    public string Item_ID { get; set; }
}

public partial class AddtoRetrievelnew1_Result
{
    public int Requisition_ID { get; set; }
    public string Status { get; set; }
    public string Item_ID { get; set; }
}

public partial class AllCategories_Result
{
    public string Item_Number { get; set; }
    public string Description { get; set; }
}

public partial class CategoriesByItemNumber_Result
{
    public string Item_Number { get; set; }
    public string Description { get; set; }
}

public partial class CategoriesByName_Result
{
    public string Item_Number { get; set; }
    public string Description { get; set; }
}

public partial class DateComparisonChart_Result
{
    public string Department_Name { get; set; }
    public string Category { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
}

public partial class DEMOProcedure_Result
{
    public string Category { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public Nullable<int> Quantity { get; set; }
}

public partial class getAllDepartmentNames_Result
{
    public string Department_Name { get; set; }
    public string Department_ID { get; set; }
}

public partial class getDisbursementsBydeptID_Result
{
    public int Product_Disbursement_ID { get; set; }
    public string Item_ID { get; set; }
    public string Department_ID { get; set; }
    public Nullable<int> IOU_Quantity { get; set; }
    public Nullable<int> Requested_Quantity { get; set; }
    public Nullable<int> Delivery_Quantity { get; set; }
    public Nullable<int> Return_Quantity { get; set; }
    public string Signature { get; set; }
    public Nullable<System.DateTime> Delivery_Date { get; set; }
    public string Reason { get; set; }
    public string Description { get; set; }
}

public partial class getEmployeeDetails_Result
{
    public string Department_Name { get; set; }
    public string CollectionPoint_Name { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
}

public partial class GetFavourites_Result
{
    public Nullable<int> count { get; set; }
    public string item { get; set; }
    public string Description { get; set; }
}

public partial class GetOrderItems_Result
{
    public string Status { get; set; }
    public int Requisition_ID { get; set; }
    public string Item_ID { get; set; }
    public string Description { get; set; }
    public Nullable<int> Quantity { get; set; }
}

public partial class GetStationery_Result
{
    public int Requisition_ID { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public string Department_Name { get; set; }
}

public partial class iou_list_Procedure_Result
{
    public string Description { get; set; }
    public string Department_Name { get; set; }
    public Nullable<int> IOU_Quantity { get; set; }
    public Nullable<int> Total_Quantity { get; set; }
    public string Item_Number { get; set; }
}

public partial class iou_list_searchProcedure_Result
{
    public string Description { get; set; }
    public string Department_Name { get; set; }
    public Nullable<int> IOU_Quantity { get; set; }
    public Nullable<int> Total_Quantity { get; set; }
    public string Item_Number { get; set; }
    public string IOU_ID { get; set; }
    public string Department_ID { get; set; }
    public string Item_Number1 { get; set; }
    public Nullable<int> IOU_Quantity1 { get; set; }
    public string Status { get; set; }
}

public partial class PendingRequestDetails_Mobile_Result
{
    public string Description { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string Measure_Unit { get; set; }
}

public partial class PendingRequestsProcedure_Result
{
    public Nullable<int> order_quantity { get; set; }
    public int Requisition_ID { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public string Name { get; set; }
}

public partial class RetrievalList_Result
{
    public int Department_Orders_ID { get; set; }
    public string Item { get; set; }
    public string Department_Name { get; set; }
    public Nullable<int> Requisition_Quantity { get; set; }
    public Nullable<int> Fulfilled_Quantity { get; set; }
    public Nullable<int> IOU_Quantity { get; set; }
    public Nullable<int> CurrentStock { get; set; }
    public Nullable<int> Total { get; set; }
}

public partial class RetrievalListDetails_Result
{
    public int Department_Orders_ID { get; set; }
    public string Item { get; set; }
    public string Department_Name { get; set; }
    public Nullable<int> Requisition_Quantity { get; set; }
    public Nullable<int> Fulfilled_Quantity { get; set; }
    public Nullable<int> IOU_Quantity { get; set; }
    public Nullable<int> CurrentStock { get; set; }
    public Nullable<int> Total { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}

public partial class stationary_requisition_Procedure_Result
{
    public int Requisition_ID { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public string Department_Name { get; set; }
    public Nullable<int> Quantity { get; set; }
}

public partial class stationary_requisition_searchProcedure_Result
{
    public int Requisition_ID { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public string Department_Name { get; set; }
    public Nullable<int> Quantity { get; set; }
}

public partial class stationary_requisition_searchProcedure1_Result
{
    public int Requisition_ID { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public string Department_Name { get; set; }
    public Nullable<int> Quantity { get; set; }
}

public partial class StationeryForm_Result
{
    public int Requisition_ID { get; set; }
    public string Item { get; set; }
    public string Measure_Unit { get; set; }
    public Nullable<int> Quantity { get; set; }
}

public partial class StationeryRequestDetails_Result
{
    public int Requisition_ID { get; set; }
    public string Item { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string Measure_Unit { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public string Department_ID { get; set; }
}

public partial class Store_GetDisbursementList_Result
{
    public int Department_Orders_ID { get; set; }
    public string Department_ID { get; set; }
    public string Item_ID { get; set; }
    public string Description { get; set; }
    public Nullable<System.DateTime> Requisition_Date { get; set; }
    public Nullable<int> Requisition_Quantity { get; set; }
    public Nullable<int> Fulfilled_Quantity { get; set; }
    public Nullable<int> IOU_Quantity { get; set; }
    public Nullable<int> Return_Quantity { get; set; }
    public Nullable<int> Total { get; set; }
}

public partial class Supplier_Details_Result
{
    public string Supplier_ID { get; set; }
    public string ItemID { get; set; }
    public string Description { get; set; }
    public Nullable<double> Price { get; set; }
}

public partial class Validate_User_Result
{
    public Nullable<int> UserId { get; set; }
    public string Roles { get; set; }
    public Nullable<int> RoleIds { get; set; }
}
